name: ExtDN PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: extdn/github-actions-m2/magento-phpstan/8.3@master
        env:
          MAGENTO_VERSION: '2.4.7-p1'
          COMPOSER_VERSION: 2
        with:
          composer_name: ${{ secrets.COMPOSER_NAME }}
          phpstan_level: 2
          magento_pre_install_script: .github/workflows/extdn-phpstan-pre-install.sh
